### ISSUE TITLE
bug  when size of buffer not a power of 2

### ISSUE THREAD

**Issue by sramrajkar** [krkind/circularbuffer#1]
https://github.com/krkind/circularbuffer/blob/ab84593c0cfbdc3c97c09863e8b5675dda3969a6/circularbuffer.c#L87

May be to roll the pointers back use % buf size rather than &. This will work for any size of buffer.

**Comment by krkind** [comment]
> https://github.com/krkind/circularbuffer/blob/ab84593c0cfbdc3c97c09863e8b5675dda3969a6/circularbuffer.c#L87
> 
> May be to roll the pointers back use % buf size rather than &. This will work for any size of buffer.

Yes for CircularBufferPushBack and CircularBufferPopFront it would work, but will not for CircularBufferPeek as I wanted it to be both efficient and thread safe. With power of 2 it work to calculate number of added element with:

    const size_t size = ((write_pos - read_pos) & ctx->max_size);
